RecipeFormatVersion: '2020-01-25'
ComponentName: COMPONENT_NAME
ComponentVersion: COMPONENT_VERSION
ComponentDescription: The Things Stack LoRaWAN
ComponentPublisher: Amazon
ComponentConfiguration:
  DefaultConfiguration:
    secretArn: $SECRET_ARN
    accessControl:
      aws.greengrass.SecretManager:
        aws.greengrass.labs.TheThingsStackLoRaWAN:secrets:1:
          policyDescription: Allows access to The Things Stack configuration secret
          operations:
          - "aws.greengrass#GetSecretValue"
          resources:
          - $SECRET_ARN
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: '>=2.0.0'
  aws.greengrass.SecretManager:
    VersionRequirement: '>=2.0.0'
    DependencyType: HARD
Manifests:
- Platform:
    os: linux
  Lifecycle:
    Install:
      RequiresPrivilege: true
      Script: |-
        cp -R {artifacts:decompressedPath}/tts/* .
        echo Creating virtual environment
        python3 -m venv venv
        echo Activating virtual environment
        . venv/bin/activate
        echo Upgrading pip
        pip install pip --upgrade
        echo Installing package requirements
        pip3 install awsiotsdk PyYAML
        echo Installing the component artifacts
        python3 -u install.py {configuration:/secretArn}
    Startup:
      RequiresPrivilege: true
      Script: |-
        echo Activating virtual environment
        . venv/bin/activate
        echo Running the component
        python3 -u share_certs.py
        docker compose up -d stack
    Shutdown:
      RequiresPrivilege: true
      Script: docker compose down
    Recover:
      RequiresPrivilege: true
      Script: docker compose down
  Artifacts:
  - Uri: docker:$DOCKER_IMAGE_TTS
  - Uri: docker:$DOCKER_IMAGE_DB
  - Uri: docker:$DOCKER_IMAGE_REDIS
  - Uri: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/tts.zip
    Unarchive: ZIP
    Permission:
      Read: ALL
Lifecycle: {}
